(() => {
  const dataUrl = "https://data.incovid19.org/v4/min/data.min.json";
  const timeSeriesUrl = "https://data.incovid19.org/v4/min/timeseries.min.json";
  const stateNames = {AN:"Andaman and Nicobar Islands",AP:"Andhra Pradesh",AR:"Arunachal Pradesh",AS:"Assam",BR:"Bihar",CH:"Chandigarh",CT:"Chhattisgarh",DN:"Dadra and Nagar Haveli and Daman and Diu",DL:"Delhi",GA:"Goa",GJ:"Gujarat",HR:"Haryana",HP:"Himachal Pradesh",JK:"Jammu and Kashmir",JH:"Jharkhand",KA:"Karnataka",KL:"Kerala",LA:"Ladakh",LD:"Lakshadweep",MP:"Madhya Pradesh",MH:"Maharashtra",MN:"Manipur",ML:"Meghalaya",MZ:"Mizoram",NL:"Nagaland",OR:"Odisha",PY:"Puducherry",PB:"Punjab",RJ:"Rajasthan",SK:"Sikkim",TN:"Tamil Nadu",TG:"Telangana",TR:"Tripura",UP:"Uttar Pradesh",UT:"Uttarakhand",WB:"West Bengal"};
  const number = value => new Intl.NumberFormat("en-IN", {notation:"compact",maximumFractionDigits:1}).format(Number(value)||0);
  const fullNumber = value => new Intl.NumberFormat("en-IN").format(Number(value)||0);
  const date = value => value ? new Date(value).toLocaleDateString("en-IN",{day:"numeric",month:"short",year:"numeric"}) : "Not reported";
  const total = (record,key) => Number(record?.total?.[key]||0);
  const status = document.querySelector("#data-status strong");
  const stateData = {};
  function setMetric(id,value){const el=document.getElementById(id);el.textContent=number(value);el.title=fullNumber(value)}
  function card(code,item){stateData[code]=item;const values=[["Confirmed","confirmed",total(item,"confirmed")],["Recovered","recovered",total(item,"recovered")],["Deceased","deceased",total(item,"deceased")],["Dose 1","",total(item,"vaccinated1")],["Dose 2","",total(item,"vaccinated2")]];return `<article class="state-card" data-state="${stateNames[code].toLowerCase()}"><h3 class="state-title">${stateNames[code]}</h3>${values.map(([label,kind,value])=>`<div class="state-stat ${kind}"><span>${label}</span><strong title="${fullNumber(value)}">${number(value)}</strong></div>`).join("")}<button class="drilldown" data-state-code="${code}">View district data <i class="fa-solid fa-arrow-right"></i></button><p class="state-updated">Updated ${date(item?.meta?.last_updated)}</p></article>`}
  function showDistricts(code){const districts=Object.entries(stateData[code]?.districts||{}).sort((a,b)=>total(b[1],"confirmed")-total(a[1],"confirmed")),view=document.getElementById("district-view");document.getElementById("district-title").textContent=`${stateNames[code]} districts`;document.getElementById("district-data").innerHTML=districts.length?districts.map(([name,item])=>`<article class="district-card"><h3>${name}</h3><div class="state-stat confirmed"><span>Confirmed</span><strong>${number(total(item,"confirmed"))}</strong></div><div class="state-stat recovered"><span>Recovered</span><strong>${number(total(item,"recovered"))}</strong></div><div class="state-stat deceased"><span>Deceased</span><strong>${number(total(item,"deceased"))}</strong></div><div class="state-stat"><span>First dose</span><strong>${number(total(item,"vaccinated1"))}</strong></div><div class="state-stat"><span>Second dose</span><strong>${number(total(item,"vaccinated2"))}</strong></div></article>`).join(""):'<p class="loading">District-level data is not available for this state.</p>';view.hidden=false;view.scrollIntoView({behavior:"smooth",block:"start"})}
  function renderChart(canvas,labels,datasets){const chart=new Chart(canvas.getContext("2d"),{type:"line",data:{labels,datasets:datasets.map(d=>({...d,fill:false,borderWidth:2,pointRadius:0,pointHoverRadius:6,pointHitRadius:14,lineTension:.28}))},options:{responsive:true,maintainAspectRatio:false,hover:{mode:"index",intersect:false,animationDuration:0},layout:{padding:{bottom:18}},legend:{display:false},tooltips:{enabled:false},scales:{xAxes:[{gridLines:{display:false},ticks:{fontSize:9,fontColor:"#8b96a7",padding:12,maxRotation:0,autoSkip:true,maxTicksLimit:12}}],yAxes:[{gridLines:{color:"#eef1f5",drawBorder:false},ticks:{fontSize:10,fontColor:"#8b96a7",callback:value=>number(value)}}]}}});addHoverTooltip(chart);return chart}
  function addHoverTooltip(chart){const canvas=chart.canvas,tip=document.createElement("div");tip.className="chart-hover";canvas.parentElement.appendChild(tip);canvas.addEventListener("mousemove",event=>{const bounds=canvas.getBoundingClientRect(),area=chart.chartArea,x=event.clientX-bounds.left,y=event.clientY-bounds.top;if(x<area.left||x>area.right||y<area.top||y>area.bottom){tip.classList.remove("visible");return}const progress=(x-area.left)/(area.right-area.left);const index=Math.max(0,Math.min(chart.data.labels.length-1,Math.round(progress*(chart.data.labels.length-1))));const rows=chart.data.datasets.map(dataset=>({dataset,value:dataset.data[index]})),title=chart.hoverLabels?.[index]||chart.data.labels[index];tip.innerHTML=`<strong>${title}</strong>${rows.map(({dataset,value})=>`<div><span>${dataset.label}</span><b>${fullNumber(value)}</b></div>`).join("")}`;tip.style.left=`${Math.min(x+14,bounds.width-170)}px`;tip.style.top=`${Math.max(y-20,8)}px`;tip.classList.add("visible")});canvas.addEventListener("mouseleave",()=>tip.classList.remove("visible"))}
  function addLegendControls(chart,name){const buttons=[...document.querySelectorAll(`[data-legend="${name}"] button`)],visible=new Set(chart.data.datasets.map((_,index)=>index)),allDatasets=chart.data.datasets.map(dataset=>({...dataset,data:dataset.data.slice()}));buttons.forEach(button=>button.addEventListener("click",()=>{const index=Number(button.dataset.series);if(visible.has(index)){if(visible.size===1)return;visible.delete(index)}else visible.add(index);chart.data.datasets=allDatasets.filter((_,datasetIndex)=>visible.has(datasetIndex)).map(dataset=>({...dataset,data:dataset.data.slice()}));buttons.forEach(item=>item.classList.toggle("active",visible.has(Number(item.dataset.series))));chart.update()}))}
  const sets = points => [{label:"Confirmed",data:points.map(([,v])=>total(v,"confirmed")),borderColor:"#e49728",backgroundColor:"#e49728"},{label:"Recovered",data:points.map(([,v])=>total(v,"recovered")),borderColor:"#17a672",backgroundColor:"#17a672"},{label:"Deceased",data:points.map(([,v])=>total(v,"deceased")),borderColor:"#df5a5a",backgroundColor:"#df5a5a"}];
  async function loadTotals(){const response=await fetch(dataUrl);if(!response.ok)throw Error();const data=await response.json(),india=data.TT;[["confirmed","confirmed"],["recovered","recovered"],["deaths","deceased"],["tested","tested"],["vaccinated1","vaccinated1"],["vaccinated2","vaccinated2"]].forEach(([id,key])=>setMetric(id,total(india,key)));const entries=Object.entries(data).filter(([code])=>code!=="TT"&&stateNames[code]).sort((a,b)=>total(b[1],"confirmed")-total(a[1],"confirmed"));document.getElementById("state-data").innerHTML=entries.map(([code,item])=>card(code,item)).join("");const stateChart=renderChart(document.getElementById("myChartstatewise"),entries.map(([code])=>code),sets(entries));stateChart.hoverLabels=entries.map(([code])=>stateNames[code]);addLegendControls(stateChart,"state");status.textContent=`Last reported ${date(india?.meta?.last_updated)}`}
  async function loadTrend(){const response=await fetch(timeSeriesUrl);if(!response.ok)throw Error();const data=await response.json(),points=Object.entries(data.TT?.dates||{}).slice(-180);addLegendControls(renderChart(document.getElementById("myChartdatewise"),points.map(([key])=>date(key)),sets(points)),"trend")}
  document.getElementById("state-search").addEventListener("input",event=>{const query=event.target.value.trim().toLowerCase(),cards=[...document.querySelectorAll(".state-card")];let shown=0;cards.forEach(item=>{const match=item.dataset.state.includes(query);item.hidden=!match;shown+=match});document.querySelector(".empty")?.remove();if(!shown)document.getElementById("state-data").insertAdjacentHTML("beforeend",'<p class="empty">No states match that search.</p>')});
  document.getElementById("state-data").addEventListener("click",event=>{const button=event.target.closest("[data-state-code]");if(button)showDistricts(button.dataset.stateCode)});
  document.getElementById("back-to-states").addEventListener("click",()=>{document.getElementById("district-view").hidden=true;document.getElementById("states").scrollIntoView({behavior:"smooth",block:"start"})});
  Promise.all([loadTotals(),loadTrend()]).catch(()=>{status.textContent="Data source is temporarily unavailable";const area=document.getElementById("state-data");if(!area.querySelector(".state-card"))area.innerHTML='<p class="loading error">We could not load the latest data. Please try again later.</p>'});
})();
